---
# Default state for all rules
default: true

# Line length
MD013:
  line_length: 120
  code_blocks: false
  tables: false

# Multiple headers with the same content
MD024:
  allow_different_nesting: true

# Trailing punctuation in header
MD026: false

# Inline HTML
MD033: false

# Fenced code blocks should have a language specified
MD040: true

# First line in a file should be a top-level header
MD041: false
