name: CI with Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'  # Using the latest Python 3.13

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.3.2
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install dependencies
      run: |
        poetry install --no-interaction

    - name: Lint with flake8
      run: |
        poetry run flake8 src tests

    - name: Check formatting with black
      run: |
        poetry run black --check src tests

    - name: Test with pytest and coverage
      run: |
        poetry run pytest --cov=src --cov-report=xml --cov-report=html --junitxml=reports/results.xml
        poetry run coverage html -d reports/coverage

    - name: Check coverage threshold
      run: |
        poetry run coverage report --fail-under=70

    - name: Upload coverage artifacts
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: reports/coverage/

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: reports/results.xml
